import { LessonLink } from "../types/types";

export const lessonLinks: LessonLink[] = [
  {
    id: "basic-001",
    title: "Basic usage of 'I'm'",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2001",
    content: {
      title: "Basic usage of 'I'm'",
      detail1:
        "I'm is short for I am. We use it when talking about ourselves or what we are doing right now.",
      example1: [
        "I'm ready to start.",
        "I'm looking for my keys.",
        "I'm feeling great today.",
        "I'm learning English.",
        "I'm watching a movie.",
        "I'm cooking dinner.",
        "I'm waiting for a friend.",
        "I'm visiting my family this weekend.",
        "I'm tired, I will rest now.",
        "I'm grateful for your help.",
      ],
      detail2:
        "Here is a simple set of fresh examples using descriptive words with I'm, just like you asked, in easy, everyday English sentences:",
      example2: [
        "I'm very happy.",
        "I'm extremely tired.",
        "I'm terribly hungry.",
      ],
      titleGuj: "I'm નો મૂળભૂત ઉપયોગ",
      detail1Guj:
        "I'm એ I am નું સંક્ષિપ્ત સ્વરૂપ છે. અમે તેનો ઉપયોગ ત્યારે કરીએ છીએ જ્યારે પોતે કે હાલ શું કરી રહ્યા હોઈએ તે વિશે વાત કરીએ.",
      example1Guj: [
        "હું શરૂ કરવા માટે તૈયાર છું.",
        "હું મારી ચાબીઓ શોધી રહ્યો છું.",
        "હું આજ ખૂબ સારું અનુભવું છું.",
        "હું અંગ્રેજી શીખું છું.",
        "હું ફિલ્મ જોઈ રહ્યો છું.",
        "હું ડિનર પકાવી રહ્યો છું.",
        "હું મિત્રની રાહ જોઈ રહ્યો છું.",
        "હું આ વીકએન્ડે મારા પરિવારની મુલાકાત લઉં છું.",
        "હું થાકેલો છું, હવે આરામ કરીશ.",
        "હું તમારી મદદ માટે આભારી છું.",
      ],
      detail2Guj:
        "અહીં “I’m” (હું છું) સાથેના કેટલાક સરળ અને નવા ઉદાહરણો આપેલા છે, જે વર્ણનાત્મક શબ્દોનો ઉપયોગ કરે છે અને દૈનિક બોલચાલની સરળ અંગ્રેજી વાક્યોમાં છે.",
      example2Guj: [
        "હું ખૂબ ખુશ છું.",
        "હું અત્યંત થાકેલો છું.",
        "હું ખૂબ ભૂખ્યો છું.",
      ],
    },
  },
  {
    id: "basic-002",
    title: "Using 'in', 'at', 'on' with I'm",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2002",
    content: {
      title: "Using 'in', 'at', 'on' with I'm",
      detail1:
        "'In' is used to describe being inside a place or room. 'At' is used for a general location or a specific point such as a place or building.",
      example1: [
        "I'm in the kitchen.",
        "I'm in my bedroom.",
        "I'm at the gym.",
        "I'm in a taxi.",
        "I'm in the garden.",
        "I'm at the bus stop.",
        "I'm at the train station.",
        "I'm at school.",
        "I'm at the hospital.",
        "I'm at the restaurant.",
      ],
      detail2:
        "'On' is used for surfaces, communication devices, and some types of transport.",
      example2: [
        "I'm on the phone.",
        "I'm on my computer.",
        "I'm on the bus.",
        "I'm on the roof.",
        "I'm on the internet.",
      ],
      titleGuj: "I'm માં 'in', 'at', 'on' ના વિવિધ ઉપયોગ",
      detail1Guj:
        "'in' નો ઉપયોગ કોઈ જગ્યા અથવા રૂમ (શારીરિક સ્થળ)માં હોવા માટે થાય છે. જ્યારે 'at' નો ઉપયોગ સામાન્ય સ્થાન કે ચોક્કસ બિંદુ માટે થાય છે જેમ કે કોઈ જગ્યા કે બિલ્ડિંગ.",
      example1Guj: [
        "હું રસોડામાં છું.",
        "હું મારા બેડરૂમમાં છું.",
        "હું જીમમાં છું.",
        "હું ટૅક્સીમાં છું.",
        "હું બગીચામાં છું.",
        "હું બસ સ્ટોપ પર છું.",
        "હું ટ્રેન સ્ટેશન પર છું.",
        "હું શાળામાં છું.",
        "હું હોસ્પિટલ ખાતે છું.",
        "હું રેસ્ટોરન્ટમાં છું.",
      ],
      detail2Guj:
        "'on' નો ઉપયોગ સપાટીઓ, સંવાદ સાધનો અને કેટલાક પ્રકારના પરિવહનમાં થાય છે.",
      example2Guj: [
        "હું ફોન પર છું.",
        "હું મારા કમ્પ્યુટર પર છું.",
        "હું બસમાં છું.",
        "હું છત પર છું.",
        "હું ઈન્ટરનેટ પર છું.",
      ],
    },
  },
  {
    id: "basic-003",
    title: "I'm good at ...",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2003",
    content: {
      title: "I'm good at ...",
      detail1:
        "'I'm good at ...' means you have skill or ability in that activity.",
      example1: [
        "I'm good at singing.",
        "I'm good at cooking.",
        "I'm good at playing football.",
        "I'm good at drawing.",
        "I'm good at solving puzzles.",
        "I'm good at learning new words.",
        "I'm good at dancing.",
        "I'm good at writing stories.",
        "I'm good at swimming.",
        "I'm good at playing chess.",
      ],
      titleGuj: "હું ... માં સારો છું",
      detail1Guj:
        "'I'm good at ...' નો અર્થ છે કે તમને તે કાર્યમાં કુશળતા અથવા ક્ષમતા છે",
      example1Guj: [
        "હું ગીત ગાવામાં સારો છું.",
        "હું રસોઈમાં સારો છું.",
        "હું ફૂટબૉલ રમવામાં સારો છું.",
        "હું ચિત્ર બનાવવામાં સારો છું.",
        "હું પઝલ ઉકેલવામાં સારો છું.",
        "હું નવા શબ્દો શીખવામાં સારો છું.",
        "હું નૃત્ય કરવામાં સારો છું.",
        "હું વાર્તાઓ લખવામાં સારો છું.",
        "હું તરવામાં સારો છું.",
        "હું ચેસ રમવામાં સારો છું.",
      ],
    },
  },
  {
    id: "basic-004",
    title: "I'm + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2005",
    content: {
      title: "I'm + (verb)",
      detail1:
        "'I'm' is the short form of 'I am'. Used with a verb to describe an action or state about yourself.",
      example1: [
        "I'm having breakfast.",
        "I'm washing my hands.",
        "I'm happy.",
        "I'm going to school.",
        "I'm reading a book.",
        "I'm talking to a friend.",
      ],
      titleGuj: "I'm + (ક્રિયા)",
      detail1Guj:
        "'I'm' એ 'I am' નું સંક્ષિપ્ત સ્વરૂપ છે. ક્રિયા સાથે ઉપયોગ કરીને તે તમારા વિશે કોઇ ક્રિયા કે સ્થિતિ દર્શાવે છે.",
      example1Guj: [
        "હું નાસ્તો કરી રહ્યો છું.",
        "હું હાથ ધોઈ રહ્યો છું.",
        "હું ખુશ છું.",
        "હું શાળાએ જઈ રહ્યો છું.",
        "હું પુસ્તક વાંચી રહ્યો છું.",
        "હું મિત્ર સાથે વાત કરી રહ્યો છું.",
      ],
    },
  },
  {
    id: "basic-005",
    title: "I'm getting",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2006",
    content: {
      title: "I'm getting",
      detail1:
        "'I'm getting' means you are currently experiencing, obtaining, or improving something. It indicates a change or process happening now or in the near future.",
      example1: [
        "I'm getting stronger every day.",
        "I'm getting ready for my trip.",
        "I'm getting hungry.",
        "I'm getting better at cooking.",
        "I'm getting new books.",
        "I'm getting my hair cut tomorrow.",
        "I'm getting excited for the party.",
        "I'm getting my homework done.",
        "I'm getting tired quickly.",
      ],
      titleGuj: "I'm getting",
      detail1Guj:
        "'I'm getting'નો અર્થ થાય છે કે તમે હાલમાં કંઈક અનુભવ કરી રહ્યા છો, મેળવી રહ્યા છો અથવા સુધરી રહ્યા છો. આ હાલ કે નજીકના ભવિષ્યમાં બદલાવ કે પ્રક્રિયા દર્શાવે છે.",
      example1Guj: [
        "હું દરરોજ વધુ મજબૂત થઈ રહ્યો છું.",
        "હું મારી યાત્રા માટે તૈયાર થઈ રહ્યો છું.",
        "હું ભૂખ્યો થઈ રહ્યો છું.",
        "હું રસોઈમાં વધુ સારો થઈ રહ્યો છું.",
        "હું નવા પુસ્તકો મેળવી રહ્યો છું.",
        "હું કાલે વાળ કપાવવા જઈ રહ્યો છું.",
        "હું પાર્ટી માટે ઉત્સાહિત થઈ રહ્યો છું.",
        "હું હોમવર્ક પૂરું કરી રહ્યો છું.",
        "હું ઝડપથી થાક્યો થઈ રહ્યો છું.",
      ],
    },
  },
  {
    id: "basic-006",
    title: "I'm trying + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2007",
    content: {
      title: "I'm trying + (verb)",
      detail1:
        "'I'm trying' means you are making an effort to do something or trying to achieve a goal. It shows ongoing effort or intention.",
      example1: [
        "I'm trying to learn a new language.",
        "I'm trying to eat healthier.",
        "I'm trying to save money for a new phone.",
        "I'm trying to be more patient.",
        "I'm trying to exercise every day.",
        "I'm trying to improve my English.",
        "I'm trying to quit bad habits.",
      ],
      detail2:
        "'Trying' is also used as an adjective to describe a stressful or emotionally difficult experience.",
      example2: [
        "Learning new things can be trying.",
        "The marathon was very trying for me.",
        "Studying all night was trying for the whole class.",
        "The long journey was trying for everyone.",
        "The big exam was trying my patience.",
      ],
      titleGuj: "I'm trying + (ક્રિયા)",
      detail1Guj:
        "'I'm trying'નો અર્થ થાય છે કે તમે કંઈક કરવાની કોશિશ કરી રહ્યા છો અથવા કોઈ લક્ષ્ય હાંસલ કરવા પ્રયાસમાં છો. આ ચાલુ પ્રયત્ન કે ઇરાદા દર્શાવે છે.",
      example1Guj: [
        "હું નવી ભાષા શીખવાનો પ્રયાસ કરી રહ્યો છું.",
        "હું વધુ સ્વસ્થ ખાવાની કોશિશ કરી રહ્યો છું.",
        "હું નવા ફોન માટે પૈસા બચાવવાનો પ્રયાસ કરી રહ્યો છું.",
        "હું વધુ ધીરજવાન બનવાનો પ્રયાસ કરી રહ્યો છું.",
        "હું દરરોજ વ્યાયામ કરવાનો પ્રયાસ કરી રહ્યો છું.",
        "હું મારી અંગ્રેજી સુધારવાનો પ્રયાસ કરી રહ્યો છું.",
        "હું ખરાબ આદતો છોડવાનો પ્રયાસ કરી રહ્યો છું.",
      ],
      detail2Guj:
        "'Trying' એક વિશેષણ તરીકે પણ વપરાય છે જે તણાવ, કષ્ટ અથવા ભાવનાત્મક કષ્ટ દર્શાવે છે. તે એવી સ્થિતિ કે અનુભવ બતાવે છે જે સહન કરવી મુશ્કેલ હોય.",
      example2Guj: [
        "નવી વસ્તુઓ શીખવી ક્યારેક મુશ્કેલ થઈ શકે છે.",
        "તે મેરેથોન મારા માટે ખૂબ જ કઠિન રહ્યું.",
        "રાતભર અભ્યાસ કરવો આખા વર્ગ માટે કષ્ટદાયક હતો.",
        "લાંબી મુસાફરી સૌ માટે કઠિન હતી.",
        "મોટી પરીક્ષા મારી સહનશક્તિની કસોટી લઈ રહી હતી.",
      ],
    },
  },
  {
    id: "basic-007",
    title: "I'm gonna + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2008",
    content: {
      title: "I'm gonna + (verb)",
      detail1:
        "'Gonna' is the informal short form of 'going to', mainly used in spoken English and informal writing. It indicates intention to do something in the future.",
      example1: [
        "I'm gonna drink coffee.",
        "I'm gonna go to work.",
        "I'm gonna eat cake.",
        "I'm gonna send my resume.",
        "I'm gonna run a marathon.",
        "I'm gonna invite him for dinner.",
        "I'm gonna quit smoking.",
        "I'm gonna help my friends.",
        "I'm gonna read a book.",
      ],
      titleGuj: "I'm gonna + (ક્રિયા)",
      detail1Guj:
        "'gonna' એ 'going to' નું અનૌપચારિક સંક્ષિપ્ત સ્વરૂપ છે જે મુખ્યત્વે બોલચાલની અંગ્રેજીમાં અને અનૌપચારિક લેખનમાં વપરાય છે. તેનો ઉપયોગ ભવિષ્યમાં કોઈ ક્રિયા કરવાના ઇરાદા દર્શાવવા માટે થાય છે.",
      example1Guj: [
        "હું કૉફી પીવાનો છું.",
        "હું કામ પર જઈશ.",
        "હું કેક ખાઈશ.",
        "હું મારો રિઝ્યુમ મોકલીશ.",
        "હું મેરેથોન દોડિશ.",
        "હું તેને રાત્રિભોજન માટે આમંત્રિત કરવાનો છું.",
        "હું ધૂમ્રપાન છોડી દઈશ.",
        "હું મારા મિત્રોની મદદ કરવા જઇ રહ્યો છું.",
        "હું એક પુસ્તક વાંચવાનો છું.",
      ],
    },
  },
  {
    id: "basic-008",
    title: "I have + (noun)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2009",
    content: {
      title: "I have + (noun)",
      detail1: "'I have' is used to show possession or ownership of something.",
      example1: [
        "I have a new phone.",
        "I have two brothers.",
        "I have concert tickets.",
        "I have a computer.",
        "I have a question.",
        "I have a job.",
      ],
      detail2:
        "'I have' with 'cannot' and 'won't' is used to show rules or limits that you don't allow.",
      example2: [
        "I cannot smoke in my car.",
        "I won't bring dogs into the house.",
        "I don't allow my work to be stopped.",
        "I don't allow bad behavior in school.",
      ],
      titleGuj: "I have + (નામપદ)",
      detail1Guj:
        "'I have' નો ઉપયોગ માલિકી અથવા કઈક ધરાવવાનો દર્શાવવા માટે થાય છે.",
      example1Guj: [
        "મારી પાસે નવો ફોન છે.",
        "મારા બે ભાઈઓ છે.",
        "મારી પાસે શોના ટિકિટ્સ છે.",
        "મારી પાસે કમ્પ્યુટર છે.",
        "મારા પાસે એક પ્રશ્ન છે.",
        "મારી પાસે નોકરી છે.",
      ],
      detail2Guj:
        "'I have' સાથે 'cannot' અને 'won't' નો ઉપયોગ કોઈ નિયમો કે મર્યાદા દર્શાવવા માટે થાય છે કે જે તમે મંજૂર નથી કરતા.",
      example2Guj: [
        "હું મારી કારમાં ધુમ્રપાન કરતો નથી.",
        "હું ઘરમાં કૂતરા લાવતો નથી.",
        "હું મારી કામ અટકવા નહીં દઈશ.",
        "હું શાળામાં ખરાબ વર્તન સહન કરતો નથી.",
      ],
    },
  },
  {
    id: "basic-009",
    title: "I have + (past participle)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2010",
    content: {
      title: "I have + (past participle)",
      detail1:
        "'I have' with past participle is used to talk about actions completed or life experiences.",
      example1: [
        "I have finished my homework.",
        "I have visited many countries.",
        "I have lost my keys.",
        "I have cooked dinner.",
        "I have broken my phone.",
        "I have written three emails today.",
        "I have seen this movie twice.",
        "I have cleaned my room.",
        "I have called my friend.",
      ],
      titleGuj: "I have + (ભૂતકાળ participle)",
      detail1Guj:
        "'I have' સાથે ભૂતકાળ participle નો ઉપયોગ અગાઉ થયેલી ક્રિયા કે જીવનનો અનુભવ બતાવવા માટે થાય છે.",
      example1Guj: [
        "હું મારું હોમવર્ક પૂરું કરી દીધું છે.",
        "હું ઘણા દેશોની મુલાકાત લીધી છે.",
        "હું મારી ચાબીઓ ખોવી દીધી છે.",
        "મેં રાત્રિભોજન બનાવ્યું છે.",
        "મેં મારું ફોન તોડી દીધું છે.",
        "મેં આજે ત્રણ ઈમેઈલ લખ્યાં છે.",
        "હું આ ફિલ્મ બે વાર જોઈ છે.",
        "હું મારું રૂમ સાફ કર્યું છે.",
        "મેં મારા મિત્રને ફોન કર્યો છે.",
      ],
    },
  },
  {
    id: "basic-010",
    title: "I used to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2011",
    content: {
      title: "I used to + (verb)",
      detail1:
        "'Used to' expresses past habitual actions or habits that no longer happen.",
      example1: [
        "I used to ride a bike to school.",
        "I used to visit my grandparents every summer.",
        "I used to play football on Saturdays.",
        "I used to listen to the radio in the car.",
        "I used to wear glasses.",
        "I used to drink tea, not coffee.",
        "I used to swim in the pond.",
      ],
      titleGuj: "I used to + (ક્રિયા)",
      detail1Guj:
        "'Used to' એ ભૂતકાળમાં વારંવાર થતી પ્રવૃત્તિઓ કે આદતો દર્શાવે છે જે હવે નથી.",
      example1Guj: [
        "હું સ્કૂલ જવા માટે સાયકલ ચલાવતા હતો.",
        "હું દરેક ઉનાળે દાદા-દાદીને મળવા જતો હતો.",
        "હું શનિવારે ફૂટબોલ રમતો હતો.",
        "હું કારમાં રેડિયો સાંભળતો હતો.",
        "હું ચશ્મા પહેરતો હતો.",
        "હું કૉફી નહીં, ચા પીતો હતો.",
        "હું તળાવમાં તરતો હતો.",
      ],
    },
  },
  {
    id: "basic-011",
    title: "I'm going to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2012",
    content: {
      title: "I'm going to + (verb)",
      detail1:
        "'I'm going to' expresses planned actions or intentions in the near future.",
      example1: [
        "I'm going to travel next week.",
        "I'm going to buy a new car.",
        "I'm going to study tonight.",
        "I'm going to meet my friends tomorrow.",
        "I'm going to cook dinner.",
        "I'm going to watch a movie.",
        "I'm going to call my parents.",
      ],
      titleGuj: "I'm going to + (ક્રિયા)",
      detail1Guj:
        "'I'm going to' નો અર્થ થાય છે કે તમે નજીકના ભવિષ્યમાં કોઇ યોજના કે ઈરાદો ધરાવો છો.",
      example1Guj: [
        "હું આવતા અઠવાડિયામાં પ્રવાસ કરવા જઈ રહ્યો છું.",
        "હું નવી ગાડી ખરીદવા જઈ રહ્યો છું.",
        "હું આજે રાત્રે અભ્યાસ કરવા જઈ રહ્યો છું.",
        "હું આવતીકાલે મારા મિત્રો સાથે મળવા જઈ રહ્યો છું.",
        "હું રાત્રિભોજન બનાવવાનો છું.",
        "હું એક ફિલ્મ જોવા જઈ રહ્યો છું.",
        "હું મારા માતાપિતાને ફોન કરવાનો છું.",
      ],
    },
  },
  {
    id: "basic-012",
    title: "I'm + adjective",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2013",
    content: {
      title: "I'm + adjective",
      detail1:
        "'I'm' used with adjectives to describe feelings, emotions, or states.",
      example1: [
        "I'm happy.",
        "I'm sad.",
        "I'm tired.",
        "I'm excited.",
        "I'm nervous.",
        "I'm angry.",
        "I'm bored.",
        "I'm hungry.",
      ],
      titleGuj: "I'm + વિશેષણ",
      detail1Guj:
        "'I'm' નું ઉપયોગ વિશેષણ સાથે થાય છે જે ભાવનાઓ, લાગણીઓ અથવા સ્થિતિઓ બતાવે છે.",
      example1Guj: [
        "હું ખુશ છું.",
        "હું દુઃખી છું.",
        "હું થાકેલો છું.",
        "હું ઉત્સાહિત છું.",
        "હું ચિંતિત છું.",
        "હું ગુસ્સામાં છું.",
        "હું બોર થઈ ગયો છું.",
        "હું ભૂખ્યો છું.",
      ],
    },
  },
  {
    id: "basic-013",
    title: "I'm not + (adjective/verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2014",
    content: {
      title: "I'm not + (adjective/verb)",
      detail1: "Used to make negative statements about yourself.",
      example1: [
        "I'm not tired.",
        "I'm not hungry.",
        "I'm not going.",
        "I'm not ready.",
        "I'm not sure.",
        "I'm not sleeping.",
        "I'm not busy.",
      ],
      titleGuj: "I'm not + (વિશેષણ/ક્રિયા)",
      detail1Guj: "તમારા વિશે નકારાત્મક નિવેદન કરવા માટે વપરાય છે.",
      example1Guj: [
        "હું થાકેલો નથી.",
        "હું ભૂખ્યો નથી.",
        "હું જઈ રહ્યો નથી.",
        "હું તૈયાર નથી.",
        "હું નિશ્ચિત નથી.",
        "હું ઊંઘી રહ્યો નથી.",
        "હું વ્યસ્ત નથી.",
      ],
    },
  },
  {
    id: "basic-014",
    title: "I would like to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2015",
    content: {
      title: "I would like to + (verb)",
      detail1:
        "Use 'I would like to' + verb to communicate what you want to do politely, formally, or respectfully.",
      example1: [
        "I would like to visit my friend.",
        "I would like to order a coffee.",
        "I would like to join the club.",
        "I would like to ask a question.",
        "I would like to learn English.",
        "I would like to watch that movie.",
        "I would like to invite you to dinner.",
        "I would like to hear your opinion.",
      ],
      titleGuj: "I would like to + (ક્રિયા)",
      detail1Guj:
        "'I would like to' + ક્રિયા નો ઉપયોગ નમ્ર, સત્તાવાર અથવા માન્ય રીતે તમારા ઇરાદા વ્યક્ત કરવા માટે થાય છે.",
      example1Guj: [
        "હું મારા મિત્રને મુલાકાત લેવા ઈચ્છું છું.",
        "હું કૉફી ઓર્ડર કરવી ઈચ્છું છું.",
        "હું ક્લબમાં જોડાવા માગું છું.",
        "હું એક પ્રશ્ન પૂછવા માગું છું.",
        "હું અંગ્રેજી શીખવા માગું છું.",
        "હું તે ફિલ્મ જોવા માગું છું.",
        "હું તમને રાત્રિભોજન માટે આમંત્રણ આપવા ઈચ્છું છું.",
        "હું તમારું મતો સાંભળવા માગું છું.",
      ],
    },
  },
  {
    id: "basic-015",
    title: "I plan to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2016",
    content: {
      title: "I plan to + (verb)",
      detail1:
        "The phrase 'I plan to' describes your intention or decision to do something in the near future.",
      example1: [
        "I plan to learn new things.",
        "I plan to read a book.",
        "I plan to save more money.",
        "I plan to watch a movie.",
        "I plan to impress my boss.",
        "I plan to wash my car.",
        "I plan to surprise my parents.",
        "I plan to find a new apartment.",
      ],
      titleGuj: "I plan to + (ક્રિયા)",
      detail1Guj:
        "'I plan to' વાક્યનો ઉપયોગ નજીકના ભવિષ્યમાં કોઈ કાર્ય કરવાની યોજના કે ઇરાદો દર્શાવવા માટે થાય છે.",
      example1Guj: [
        "હું નવી વસ્તુઓ શીખવાની યોજના બનાવી રહ્યો છું.",
        "હું એક પુસ્તક વાંચવાની યોજના બનાવી રહ્યો છું.",
        "હું વધુ પૈસા બચાવવાની યોજના બનાવી રહ્યો છું.",
        "હું એક ફિલ્મ જોવા ની યોજના બનાવી રહ્યો છું.",
        "હું મારા બોસને પ્રભાવિત કરવાનો પ્રયાસ કરી રહ્યો છું.",
        "હું મારી કાર ધોવાની યોજના બનાવી રહ્યો છું.",
        "હું મારા માતાપિતાને આશ્ચર્યચકિત કરવા માંગું છું.",
        "હું એક નવું ફ્લેટ શોધવાનો યોજના બનાવી રહ્યો છું.",
      ],
    },
  },
  {
    id: "basic-016",
    title: "I've decided to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2017",
    content: {
      title: "I've decided to + (verb)",
      detail1:
        "'I've' is short for 'I have,' and when combined with the word 'decided,' it means you have made a decision or come to a conclusion.",
      example1: [
        "I've decided to manage a store.",
        "I've decided to increase my workload.",
        "I've decided to accept the job.",
        "I've decided to change my bad habits.",
        "I've decided to complete my degree.",
        "I've decided to extend my membership at the gym.",
        "I've decided to hand over my responsibilities.",
        "I've decided to interview for the job.",
      ],
      titleGuj: "I've decided to + (ક્રિયા)",
      detail1Guj:
        "'I've' એટલે 'I have' નું સંક્ષિપ્ત સ્વરૂપ છે. 'Decided' સાથે મળીને, તેનો અર્થ થાય છે કે તમે કોઇ નિર્ણય લીધો છે.",
      example1Guj: [
        "મેં દુકાન ચલાવવાનો નિર્ણય કર્યો છે.",
        "મેં મારી કામની મર્યાદા વધારવાનો નિર્ણય કર્યો છે.",
        "મેં નોકરી સ્વીકારવાનો નિર્ણય કર્યો છે.",
        "મેં મારી બધી ખરાબ આદતો બદલવાનો નિર્ણય કર્યો છે.",
        "મેં ડિગ્રી પૂર્ણ કરવાનો નિર્ણય કર્યો છે.",
        "મેં જીમમાં સભ્યપદ લંબાવવાનો નિર્ણય કર્યો છે.",
        "મેં મારી જવાબદારીઓ સોંપવાનો નિર્ણય કર્યો છે.",
        "મેં નોકરી માટે ઈન્ટરવ્યુ આપવાનો નિર્ણય કર્યો છે.",
      ],
    },
  },
  {
    id: "basic-017",
    title: "I was about to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2018",
    content: {
      title: "I was about to + (verb)",
      detail1:
        "The phrase 'I was about to' is used to say that you were going to do something in the past, but something else happened that stopped you from doing it. It talks about something you intended to do but did not do.",
      example1: [
        "I was about to start cooking when the phone rang.",
        "I was about to leave the house when it started to rain.",
        "I was about to send the message, but then I changed my mind.",
        "I was about to take a shower when power went out.",
        "I was about to read a book when the doorbell rang.",
        "I was about to buy the tickets, but they sold out.",
      ],
      titleGuj: "I was about to + (ક્રિયા)",
      detail1Guj:
        "'I was about to' વાક્યનો અર્થ થાય છે કે તમે ભૂતકાળમાં કંઈક કરવાનું શરૂ કરવા જ રહ્યા હતા, પણ બીજું કંઈ થયું કે તમે કરી ન શક્યા.",
      example1Guj: [
        "જ્યારે ફોન વાગ્યો ત્યારે હું રસોઈ શરૂ કરવા જતો હતો.",
        "માટે વરસાદ પડવા લાગ્યો ત્યારે હું ઘર છોડવા જ રહ્યો હતો.",
        "હું સંદેશ મોકલવા જ રહ્યો હતો, પરંતુ પછી મન બદલી દીધું.",
        "પાવર જતાં પહેલાં હું શાવર લેવા જ રહ્યો હતો.",
        "જ્યારે દરવાજાનો બેલ વગ્યો ત્યારે હું પુસ્તક વાંચવા જતો હતો.",
        "હું ટિકિટ ખરીદવા જ રહ્યો હતો, પણ તે વેચાઈ ગઈ.",
      ],
    },
  },
  {
    id: "basic-018",
    title: "I didn't mean to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2019",
    content: {
      title: "I didn't mean to + (verb)",
      detail1:
        "The word 'didn't' is a short form of 'did not'. When combined with 'mean to', it expresses that you did something by accident or without intending to, often something you regret or feel sorry about.",
      example1: [
        "I didn't mean to interrupt you.",
        "I didn't mean to forget your birthday.",
        "I didn't mean to miss the meeting this morning.",
        "I didn't mean to send that email to the wrong person.",
        "I didn't mean to say that out loud.",
        "I didn't mean to step on your toe.",
        "I didn't mean to cause any misunderstanding.",
        "I didn't mean to call you so late.",
      ],
      titleGuj: "I didn't mean to + (ક્રિયા)",
      detail1Guj:
        "'Didn't' એટલે 'did not' નું સંક્ષિપ્ત સ્વરૂપ છે. 'Mean to' સાથે મળીને તે દર્શાવે છે કે તમે નકામું કે અનિચ્છનીય કાર્ય કર્યું છે, જે માટે તમને અફસોસ છે.",
      example1Guj: [
        "હું તમને વિક્ષેપ કરવાનું નથી માગતો.",
        "હું તમારું જન્મદિવસ ભૂલવાનું નથી માગતો.",
        "મારી ઇરાદો આ સવારે મિટિંગ ચૂકી જવાની નહોતી.",
        "હું તે ઈમેલ ખોટા વ્યક્તિને મોકલવાનું નથી માગતો.",
        "હું તે ખુલ્લેઆમ કહેવાનું નથી માગતો.",
        "હું તમારું પગ દબાવવાનું નથી માગતો.",
        "હું કોઈ ગેરસમજ સર્જવાનું નથી માગતો.",
        "હું તમને આટલી મોડે સાંજે કોલ કરવાનું નથી માગતો.",
      ],
    },
  },
  {
    id: "basic-019",
    title: "I don't have time to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2020",
    content: {
      title: "I don't have time to + (verb)",
      detail1:
        "The word 'don't' is a short form of 'do not'. When used with 'have time to', it means you are too busy or occupied to do something and cannot or will not do it right now.",
      example1: [
        "I don't have time to finish my work.",
        "I don't have time to call my friend today.",
        "I don't have time to relax this weekend.",
        "I don't have time to meet you tomorrow.",
        "I don't have time to listen to music now.",
        "I don't have time to go shopping today.",
        "I don't have time to read the news.",
        "I don't have time to exercise in the morning.",
      ],
      detail2:
        "Use 'I don't' to say things you dislike, don't understand, or don't do.",
      example2: [
        "I don't play video games.",
        "I don't eat spicy food.",
        "I don't swim in the ocean.",
        "I don't drink coffee.",
        "I don't understand Spanish.",
        "I don't eat meat.",
      ],
      titleGuj: "I don't have time to + (ક્રિયા)",
      detail1Guj:
        "'Don't' એટલે 'do not' નું સંક્ષિપ્ત સ્વરૂપ છે. જ્યારે 'have time to' સાથે વપરાય ત્યારે તેનો અર્થ થાય છે કે તમે બહુ વ્યસ્ત છો અને તમારું કામ આ સમયે નથી કરી શકતા.",
      example1Guj: [
        "મારા પાસે મારી કામગીરી પૂરી કરવા માટે સમય નથી.",
        "આજ મારા મિત્રને ફોન કરવા માટે મારી પાસે સમય નથી.",
        "આ સપ્તાહાંતે આરામ કરવા માટે મારી પાસે સમય નથી.",
        "હું આવતીકાલે તમારું મળવા માટે સમય નથી.",
        "હવે સંગીત સાંભળવા માટે મારી પાસે સમય નથી..",
        "આજ ખરીદી કરવા માટે મારી પાસે સમય નથી.",
        "સમાચાર વાંચવા માટે મારી પાસે સમય નથી.",
        "સવારે વ્યાયામ કરવા માટે મારી પાસે સમય નથી.",
      ],
      detail2Guj:
        "'I don't' નો ઉપયોગ તમે જે વસ્તુઓ પસંદ નથી કરતી, નહીં સમજતી કે નહીં કરતી તે દર્શાવવા માટે થાય છે.",
      example2Guj: [
        "હું વિડિયો ગેમ નથી રમતો.",
        "હું મસાલેદાર ખોરાક નથી ખાતો.",
        "હું સમુદ્રમાં તરતો નથી.",
        "હું કૉફી નથી પીતો.",
        "હું સ્પેનિશ ભાષા નથી સમજતો.",
        "હું માંસ નથી ખાતો.",
      ],
    },
  },
  {
    id: "basic-020",
    title: "I promise not to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2021",
    content: {
      title: "I promise not to + (verb)",
      detail1:
        "Use 'I promise not to' for making promises or assurances about actions you will avoid (to express commitments or guarantees about things you will not do).",
      example1: [
        "I promise not to cancel our plans.",
        "I promise not to use your computer without permission.",
        "I promise not to gossip about you.",
        "I promise not to break your trust.",
        "I promise not to be late again.",
        "I promise not to forget your birthday.",
      ],
      detail2:
        "The word 'promise' means to give your word that what you say is true or that you will do something. It shows you are serious about what you say.",
      example2: [
        "I promise to always support you.",
        "I promise I will take care of it.",
        "I promise I will remember your birthday.",
        "I promise to try my best.",
        "I promise I will call you tomorrow.",
        "I promise to keep your secret.",
      ],
      titleGuj: "I promise not to + (ક્રિયા)",
      detail1Guj:
        "'I promise not to' નો ઉપયોગ એવા વચનો આપવા માટે થાય છે જેમાં તમે કોઈ કામ ન કરવા માટે વચન આપો છો.",
      example1Guj: [
        "હું અમારા પ્લાન્સ રદ નહીં કરું તે વચન આપું છું.",
        "હું તમારી કમ્પ્યુટર પર ઈજાજત વગર ઉપયોગ નહીં કરું તે વચન આપું છું.",
        "હું તમારી gossip નહીં કરું તે વચન આપું છું.",
        "હું તમારું વિશ્વાસ તોડવાનો નથી તે વચન આપું છું.",
        "હું ફરીથી મોડો નહીં થઉં તે વચન આપું છું.",
        "હું તમારું જન્મદિવસ ભૂલવાનો નથી તે વચન આપું છું.",
      ],
      detail2Guj:
        "'Promise' નો અર્થ છે તમારા શબ્દ આપવો કે જે તમે કહો છો તે સાચું છે અથવા તમે કંઈક કરશો. તે દર્શાવે છે કે તમે ગંભીર છો.",
      example2Guj: [
        "હું હંમેશા તમારું સમર્થન કરવાનો વચન આપું છું.",
        "હું તેનો ધ્યાન રાખીશ તે વચન આપું છું.",
        "હું તમારું જન્મદિવસ યાદ રાખીશ તે વચન આપું છું.",
        "હું મારી શ્રેષ્ઠ કોશિશ કરીશ.",
        "હું તમને કાલે કોલ કરીશ.",
        "હું તમારું રહસ્ય રાખીશ તે વચન આપું છું.",
      ],
    },
  },
  {
    id: "basic-021",
    title: "I'd rather + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2022",
    content: {
      title: "I'd rather + (verb)",
      detail1:
        "'I'd' is short for 'I would' or 'I had.' When used with 'rather,' it means you prefer one thing over another.",
      example1: [
        "I'd rather have tea than coffee.",
        "I'd rather walk than take the bus.",
        "I'd rather study now than later.",
        "I'd rather watch a movie than read a book.",
        "I'd rather cook dinner than order food.",
        "I'd rather speak English than write it.",
      ],
      titleGuj: "I'd rather + (ક્રિયા)",
      detail1Guj:
        "'I'd' નો અર્થ 'I would' અથવા 'I had' થાય છે. જ્યારે 'rather' સાથે વપરાય ત્યારે તેનો અર્થ થાય છે કે તમે એક વસ્તુને બીજી કરતા વધારે પસંદ કરો છો.",
      example1Guj: [
        "હું કોફી કરતા ચા વધુ પસંદ કરું છું.",
        "હું બસ લેવાના બદલે ચાલવાનું વધુ પસંદ કરું છું.",
        "હું પછી કરતા હમણાં જ અધ્યયન કરવાનું વધુ પસંદ કરું છું.",
        "હું પુસ્તક વાંચવાને બદલે ફિલ્મ જોવા વધુ પસંદ કરું છું.",
        "હું ખાવા ઓર્ડર કરવાના બદલે ડિનર બનાવવાનું વધુ પસંદ કરું છું.",
        "હું અંગ્રેજી લખવા કરતાં બોલવું પસંદ કરું છું.",
      ],
    },
  },
  {
    id: "basic-022",
    title: "I feel like + (verb-ing)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2023",
    content: {
      title: "I feel like + (verb-ing)",
      detail1:
        "The phrase 'feel like' means you want to do something or that you enjoy doing it.",
      example1: [
        "I feel like reading a book.",
        "I feel like going to the beach.",
        "I feel like going for a bike ride.",
        "I feel like watching a movie.",
        "I feel like going for a walk.",
        "I feel like listening to music.",
        "I feel like dancing tonight.",
      ],
      detail2:
        "Using 'don't feel like' or 'do not feel like', You use these phrases when you want to say you do not want to do something or you do not enjoy or prefer doing it. It expresses a lack of desire or a feeling of reluctance.",
      example2: [
        "I don't feel like leaving yet.",
        "I don't feel like explaining.",
        "I don't feel like watching a movie.",
        "I don't feel like eating pizza tonight.",
        "I don't feel like going to bed.",
      ],
      titleGuj: "I feel like + (ક્રિયા-આખરે ing)",
      detail1Guj:
        "'Feel like' નો અર્થ થાય છે કે તમને કંઈક કરવા માંગ છે કે તમને એ કરવા મજા આવે છે.",
      example1Guj: [
        "મને પુસ્તક વાંચવાનું મન થાય છે.",
        "મને દરિયાકાંઠે જવાનું મન થાય છે.",
        "મને સાઇકલ પર ફરવા જવાનું મન થાય છે.",
        "મને ફિલ્મ જોવા નું મન થાય છે.",
        "મને ફરવા જવાનું મન થાય છે.",
        "મને સંગીત સાંભળવાનું મન થાય છે.",
        "મને આજે રાતે નૃત્ય કરવાનો મન છે.",
      ],
      detail2Guj:
        "'Don't feel like' અથવા 'do not feel like' નો ઉપયોગ ત્યારે થાય છે જ્યારે તમે કહેવા માંગો કે તમારું કંઈક કરવાની ઇચ્છા નથી કે તમારું તે કરવા મજા નથી આવતી.",
      example2Guj: [
        "હજુ જવાનું મન નથી",
        "હું સમજાવવાનું મન નથી કરતું.",
        "ફિલ્મ જોવા નું મન નથી.",
        "આજે રાત્રે પિઝા ખાવાનું મન નથી.",
        "સુવા જવાનું મન નથી.",
      ],
    },
  },
  {
    id: "basic-023",
    title: "I can't help + (verb-ing)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2024",
    content: {
      title: "I can't help + (verb-ing)",
      detail1:
        "The word 'can't' is a short form of 'cannot'. When combined with 'help', it means you cannot control or stop yourself from doing something. It often refers to actions or feelings that are hard to resist or avoid.",
      example1: [
        "I can't help feeling excited.",
        "I can't help thinking about the future.",
        "I can't help laughing at his jokes.",
        "I can't help worrying about the test.",
        "I can't help checking my phone all the time.",
        "I can't help smiling when I see her.",
        "I can't help eating so much.",
        "I can't help loving you.",
      ],
      titleGuj: "I can't help + (ક્રિયા-આખરે ing)",
      detail1Guj:
        "'Can't' નો અર્થ 'cannot' થાય છે. 'Help' સાથે વપરાય ત્યારે તેનો અર્થ થાય છે કે તમે કોઈ કાર્ય રોકી નથી શકો કે નિયંત્રણ કરી નથી શકો.",
      example1Guj: [
        "હું ઉત્સાહિત થવાથી રોકી શકતો નથી.",
        "હું ભવિષ્ય વિશે વિચારે વિના રહી શકતો નથી.",
        "હું તેના જોક્સ પર હસવાનું રોકી શકતો નથી.",
        "હું પરીક્ષા વિશે ચિંતા કરવાનો રોકી શકતો નથી.",
        "હું મારા ફોન ચેક કરવાનું બંધ કરી શકતો નથી.",
        "હું તેને જોઇને સ્મિત કરવાનું રોકી શકતો નથી.",
        "હું એટલું ખાવાનું રોકી શકતો નથી.",
        "હું તને પ્રેમ કરવાનો રોકી શકતો નથી.",
      ],
    },
  },
  {
    id: "basic-024",
    title: "I was busy + (verb-ing)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2025",
    content: {
      title: "I was busy + (verb-ing)",
      detail1:
        "When you use 'was', you are talking about something that happened in the past. When combined with the word 'busy', it means you were occupied with an activity or task in the past.",
      example1: [
        "I was busy learning new things.",
        "I was busy completing my homework.",
        "I was busy studying for my test.",
        "I was busy cleaning the house.",
        "I was busy talking on the phone.",
        "I was busy working.",
      ],
      detail2:
        "When you change 'was' to 'am', you talk about what you are doing now (present tense).",
      example2: [
        "I am busy talking on the phone.",
        "I am busy completing housework.",
        "I am busy studying for my test.",
        "I am busy working.",
        "I am busy cooking dinner.",
      ],
      titleGuj: "I was busy + (ક્રિયા-આખરે ing)",
      detail1Guj:
        "'Was' નો ઉપયોગ ભૂતકાળ માટે થાય છે. 'Busy' સાથે મળીને તેનો અર્થ થાય છે કે તમે ભૂતકાળમાં કોઈ કાર્યમાં વ્યસ્ત હતા.",
      example1Guj: [
        "હું નવી વસ્તુઓ શીખવામાં વ્યસ્ત હતો.",
        "હું હોમવર્ક પૂરું કરવામાં વ્યસ્ત હતો.",
        "હું મારા પરીક્ષાની તૈયારીમાં વ્યસ્ત હતો.",
        "હું ઘરની સફાઈમાં વ્યસ્ત હતો.",
        "હું ફોન પર વાત કરવામાં વ્યસ્ત હતો.",
        "હું કામમાં વ્યસ્ત હતો.",
      ],
      detail2Guj:
        "'Was' ને 'am' માં બદલવાથી તમે વર્તમાનમાં શું કરી રહ્યા છો તે બતાવો છો.",
      example2Guj: [
        "હું ફોન પર વાત કરવામાં વ્યસ્ત છું.",
        "હું ઘરના કામ પૂરાં કરવામાં વ્યસ્ત છું.",
        "હું મારી પરીક્ષા માટે અભ્યાસ કરવામાં વ્યસ્ત છું.",
        "હું કામમાં વ્યસ્ત છું.",
        "હું ડિનર બનાવવામાં વ્યસ્ત છું.",
      ],
    },
  },
  {
    id: "basic-025",
    title: "I'm not used to + (verb-ing)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2026",
    content: {
      title: "I'm not used to + (verb-ing)",
      detail1:
        "The phrase 'I'm not used to' + (verb-ing) means you are not familiar or comfortable with doing something now. It expresses that the activity feels new, strange, or difficult because you haven't done it enough to feel comfortable.",
      example1: [
        "I'm not used to talking English.",
        "I'm not used to studying so much.",
        "I'm not used to being around new people.",
        "I'm not used to speaking in front of groups of people.",
        "I'm not used to having so much stress.",
        "I'm not used to having many responsibilities.",
        "I'm not used to travelling so much.",
      ],
      titleGuj: "I'm not used to + (ક્રિયા-આખરે ing)",
      detail1Guj:
        "'I'm not used to' + (ક્રિયા-આખરે ing) નો અર્થ થાય છે કે તમે હજુ તે કાર્ય કરવા માટે પરિચિત કે આરામદાયક નથી.",
      example1Guj: [
        "હું અંગ્રેજી બોલવામાં પરિચિત નથી.",
        "હું એટલો વધુ અભ્યાસ કરવાનો આદત નથી.",
        "હું નવા લોકો સાથે રહેવામાં પરિચિત નથી.",
        "હું લોકોને સમૂહમાં બોલવામાં પરિચિત નથી.",
        "હું એટલો તણાવ લેવાનું આદત નથી.",
        "હું ઘણી જવાબદારીઓ લેવાની આદત નથી.",
        "હું એટલો પ્રવાસ કરવાનો અભ્યાસ નથી.",
      ],
    },
  },
  {
    id: "basic-026",
    title: "I want you to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2027",
    content: {
      title: "I want you to + (verb)",
      detail1:
        "'I want you to' means you would like or desire someone to do something (for desires or wishes).",
      example1: [
        "I want you to finish your homework.",
        "I want you to help me with the project.",
        "I want you to join the meeting.",
        "I want you to be honest with me.",
        "I want you to call me later.",
      ],
      detail2:
        "'I need you to' means it is necessary or very important for someone to do something (for requirements or essential actions).",
      example2: [
        "I need you to arrive on time.",
        "I need you to focus during the presentation.",
        "I need you to fix the computer.",
        "I need you to sign this document.",
        "I need you to explain the problem clearly.",
      ],
      titleGuj: "I want you to + (ક્રિયા)",
      detail1Guj:
        "'I want you to' નો અર્થ થાય છે કે તમે કોઈને કંઈક કરવા માંગો છો (ઇચ્છા માટે).",
      example1Guj: [
        "હું ઈચ્છું છું કે તમે તમારું હોમવર્ક પૂરુ કરો.",
        "હું ઈચ્છું છું કે તમે પ્રોજેક્ટમાં મારી મદદ કરો.",
        "હું ઈચ્છું છું કે તમે મીટિંગમાં જોડાઓ.",
        "હું ઈચ્છું છું કે તમે મારો સચ્ચાઈથી સામનો કરો.",
        "હું ઈચ્છું છું કે તમે મને પછી ફોન કરો.",
      ],
      detail2Guj:
        "'I need you to' નો અર્થ થાય છે કે કોઈ માટે કંઈક કરવું જરૂરી છે (આવશ્યક કાર્ય માટે).",
      example2Guj: [
        "મને જરૂર છે કે તમે સમયસર પહોંચો.",
        "મને જરૂર છે કે તમે પ્રસ્તુતિ દરમિયાન ધ્યાન આપો.",
        "મને જરૂર છે કે તમે કમ્પ્યુટર ઠીક કરો.",
        "મને જરૂર છે કે તમે આ દસ્તાવેજ પર સાઇન કરો.",
        "મને જરૂર છે કે તમે સમસ્યા સ્પષ્ટ રીતે સમજાવો..",
      ],
    },
  },
  {
    id: "basic-027",
    title: "I'm here to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2028",
    content: {
      title: "I'm here to + (verb)",
      detail1:
        "The phrase 'I'm here to' is used to tell someone that you are present at a place for a specific purpose or to accomplish something.",
      example1: [
        "I'm here to receive the award.",
        "I'm here to start the job.",
        "I'm here to raise awareness for cancer.",
        "I'm here to watch the movie.",
        "I'm here to support your decision.",
        "I'm here to receive my gift.",
        "I'm here to welcome you to the neighborhood.",
      ],
      titleGuj: "I'm here to + (ક્રિયા)",
      detail1Guj:
        "'I'm here to' નો અર્થ થાય છે કે તમે કોઈ ખાસ કારણ માટે ત્યાં હાજર છો.",
      example1Guj: [
        "હું એવોર્ડ મેળવવા અહીં આવ્યો છું.",
        "હું નોકરી શરૂ કરવા અહીં આવ્યો છું.",
        "હું કેન્સરના પ્રત્યે જાગૃતિ લાવવા અહીં આવ્યો છું.",
        "હું ફિલ્મ જોવા અહીં આવ્યો છું.",
        "હું તમારું નિર્ણય સમર્થન કરવા અહીં આવ્યો છું.",
        "હું મારું ગિફ્ટ લેવા અહીં આવ્યો છું.",
        "હું તમારું પાડોશી તરીકે આવકારવા અહીં આવ્યો છું.",
      ],
    },
  },
  {
    id: "basic-028",
    title: "I have something + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2029",
    content: {
      title: "I have something + (verb)",
      detail1:
        "The phrase 'I have something' is used to tell someone that you possess or hold something, or that you have some task, information, or responsibility that you want to express or complete.",
      example1: [
        "I have something urgent to discuss.",
        "I have something fun for us to do.",
        "I have something to ask you.",
        "I have something to attend tonight.",
        "I have something to complete.",
        "I have something to share with you.",
        "I have something special planned for your birthday.",
      ],
      titleGuj: "I have something + (ક્રિયા)",
      detail1Guj:
        "'I have something' નો ઉપયોગ કોઈને કહેવા માટે થાય છે કે તમારી પાસે કંઈક છે અથવા તમારે કંઈક કરવાનું છે.",
      example1Guj: [
        "મારા પાસે તાત્કાલિક ચર્ચા માટે કંઈક છે.",
        "મારા પાસે અમારી મજા માટે કંઈક છે.",
        "મારા પાસે તમારાથી પૂછવાનું કંઈક છે.",
        "મારા પાસે આજે રાત્રે હાજર રહેવાનું કંઈક છે.",
        "મારા પાસે પૂરું કરવાની કેટલીક બાબતો છે.",
        "મારા પાસે તમારું સાથે શેર કરવા માટે કંઈક છે.",
        "તમારા જન્મદિવસ માટે મારી પાસે ખાસ યોજના છે.",
      ],
    },
  },
  {
    id: "basic-029",
    title: "I'm looking forward to",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2030",
    content: {
      title: "I'm looking forward to",
      detail1:
        "The phrase 'I'm looking forward to' means you are excited or happy about something that will happen in the future.",
      example1: [
        "I'm looking forward to celebrating my birthday.",
        "I'm looking forward to starting my new job.",
        "I'm looking forward to seeing my friends this weekend.",
        "I'm looking forward to trying new foods.",
        "I'm looking forward to meeting you.",
        "I'm looking forward to going on vacation.",
        "I'm looking forward to learning the English language.",
      ],
      titleGuj: "I'm looking forward to",
      detail1Guj:
        "'I'm looking forward to' નો અર્થ થાય છે કે તમે ભવિષ્યમાં થનારા કાંઇક માટે ઉત્સુક કે ખુશ છો.",
      example1Guj: [
        "હું મારા જન્મદિવસ ઉજવવાનો ઈંતેજાર કરી રહ્યો છું.",
        "હું મારી નવી નોકરી શરૂ કરવાનો ઈંતેજાર કરી રહ્યો છું.",
        "હું આ વીકએન્ડે મારા મિત્રો સાથે મળવાનો ઈંતેજાર કરી રહ્યો છું.",
        "હું નવી વાનગીઓ અજમાવવા માટે ઉત્સુક છું.",
        "હું તમને મળવાનો ઈંતેજાર કરી રહ્યો છું.",
        "હું રજાઓ પર જવાનું ઈંતેજાર કરી રહ્યો છું.",
        "હું અંગ્રેજી ભાષા શીખવાનો ઈંતેજાર કરી રહ્યો છું.",
      ],
    },
  },
  {
    id: "basic-030",
    title: "I'm calling to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2031",
    content: {
      title: "I'm calling to + (verb)",
      detail1:
        "The phrase 'I'm calling to' means you are on the phone right now to do or say something specific.",
      example1: [
        "I'm calling to wish you a happy birthday.",
        "I'm calling to thank you.",
        "I'm calling to tell you about my day.",
        "I'm calling to answer your question.",
        "I'm calling to book a reservation at your restaurant.",
        "I'm calling to complain about something.",
        "I'm calling to apologize for the mistake.",
      ],
      titleGuj: "I'm calling to + (ક્રિયા)",
      detail1Guj:
        "'I'm calling to' નો અર્થ થાય છે કે તમે ફોન પર કંઈક ખાસ કરવા માટે વાત કરી રહ્યા છો.",
      example1Guj: [
        "હું તમને જન્મદિવસની શુભેચ્છા આપવા માટે કોલ કરી રહ્યો છું.",
        "હું તમારો આભાર માનવા માટે કોલ કરી રહ્યો છું.",
        "હું તમને દિવસ વિશે જણાવવા માટે કોલ કરી રહ્યો છું.",
        "હું તમારો પ્રશ્ન જવાબ આપવા માટે કોલ કરી રહ્યો છું.",
        "હું તમારા રેસ્ટોરન્ટમાં રિઝર્વેશન કરવા માટે કોલ કરી રહ્યો છું.",
        "હું કંઈક ફરિયાદ કરવા માટે કોલ કરી રહ્યો છું.",
        "હું ભૂલ માટે માફી માંગવા માટે કોલ કરી રહ્યો છું.",
      ],
    },
  },
  {
    id: "basic-031",
    title: "I'm working on + (noun)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2032",
    content: {
      title: "I'm working on + (noun)",
      detail1:
        "The phrase 'I'm working on' is used to describe putting effort—either physical or mental—into completing a task or achieving a goal.",
      example1: [
        "I'm working on my computer.",
        "I'm woking on a new idea.",
        "I'm working on painting house.",
        "I'm working on a big project.",
        "I'm working on educating my self.",
        "I'm working on my homework.",
        "I'm working on training my dog.",
      ],
      titleGuj: "",
      detail1Guj:
        "'I'm working on' નો અર્થ થાય છે કે તમે કોઈ કાર્ય અથવા લક્ષ્યાંક પર શારીરિક કે માનસિક પ્રયત્ન કરી રહ્યા છો જેથી તેને પૂર્ણ કરી શકાય.",
      example1Guj: [
        "હું મારા કમ્પ્યુટરમાં કામ કરી રહી છું.",
        "હું નવી વિચાર પર કામ કરી રહ્યો છું.",
        "હું ઘરની રંગાઈ પર કામ કરી રહી છું.",
        "હું એક મોટા પ્રોજેક્ટ પર કામ કરી રહ્યો છું.",
        "હું પોતાને શિક્ષિત કરવા પર કામ કરી રહ્યો છું.",
        "હું મારી હોમવર્ક પર કામ કરી રહી છું.",
        "હું મારા કૂતરાને તાલીમ આપવાનો પ્રયાસ કરી રહી છું.",
      ],
    },
  },
  {
    id: "basic-032",
    title: "I'm sorry to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2033",
    content: {
      title: "I'm sorry to + (verb)",
      detail1:
        "The phrase 'I'm sorry to' is used to express a feeling of sympathy or regret.",
      example1: [
        "I'm sorry to call so late.",
        "I'm sorry to brother you.",
        "I'm sorry to interrupt you.",
        "I'm sorry to miss the meeting.",
        "I'm sorry to waste your time.",
        "I'm sorry to disappoint you.",
      ],
      titleGuj: "",
      detail1Guj:
        "''I'm sorry to' વાક્યપ્રયોગનો ઉપયોગ સહાનુભૂતિ અથવા પછાતીની લાગણી વ્યક્ત કરવા માટે થાય છે.",
      example1Guj: [
        "માફ કરશો, આટલું મોડું ફોન કરવા માટે.",
        "માફ કરશો, તમને પરેશાન કરવા માટે.",
        "માફ કરશો, તમને વિક્ષેપ કરવાને માટે.",
        "માફ કરશો, મીટિંગ ચૂકી જવા માટે.",
        "માફ કરશો, તમારો સમય વ્યર્થ કરવા માટે.",
        "માફ કરશો, તમને નિરાશ કરવા માટે.",
      ],
    },
  },
  {
    id: "basic-033",
    title: "I'm thinking of + (verb-ing)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2034",
    content: {
      title: "I'm thinking of + (verb-ing)",
      detail1:
        "The phrase 'I'm thinking of' expresses the process of thought, forming an intention, plan, or judgment about something you may do or consider.",
      example1: [
        "I'm thinking of launching a new website.",
        "I'm thinking of introducing myself to him.",
        "I'm thinking of following a healthy diet.",
        "I'm thinking of increasing my workload.",
        "I'm thinking of cheking out the new movie.",
        "I'm thinking of opening up a stote.",
      ],
      titleGuj: "",
      detail1Guj:
        "‘I'm thinking of’ phrase વિચાર કરવાની પ્રક્રિયા દર્શાવે છે, જેમાં તમે કંઈક કરવા અથવા વિચારવા માટે મનમાં ઇરાદો, યોજના કે નિર્ણય બનાવો છો.",
      example1Guj: [
        "હું નવી વેબસાઇટ શરૂ કરવાની વિચારી રહ્યો છું.",
        "હું મારા પરિચય આપવા વિશે વિચારી રહ્યો છું.",
        "હું સ્વસ્થ આહારનું અનુસરણ કરવાની વિચારી રહ્યો છું.",
        "હું મારી કામની જડબેસલાક વધારવાની વિચારી રહ્યો છું.",
        "હું નવી મૂવી જોવાની વિચારી રહ્યો છું.",
        "હું દુકાન ખોલવાની વિચારી રહ્યો છું.",
      ],
    },
  },
  {
    id: "basic-034",
    title: "I'll help you + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2035",
    content: {
      title: "I'll help you + (verb)",
      detail1:
        "The phrase 'I'll help you + (verb)' means you are offering to provide assistance with something, whether it is a physical task or a mental activity.",
      example1: [
        "I'll help you learn a new skill.",
        "I'll help you fix your computer.",
        "I'll help you park your car.",
        "I'll help you move to your new house.",
        "I'll help you raise money for your charity.",
        "I'll help you cook dinner tonight.",
        "I'll help you prevent that from happening again.",
      ],
      titleGuj: "",
      detail1Guj:
        "'I'll help you + (ક્રિયા)' નો અર્થ થાય છે કે તમે કોઈ શારીરિક કાર્ય હોય કે માનસિક પ્રવૃત્તિ, તેમાં મદદ કરવાનું પ્રસ્તાવ આપી રહ્યા છો.",
      example1Guj: [
        "હું તમારી નવી કૌશલ્ય શીખવામાં મદદ કરીશ.",
        "હું તમારું કમ્પ્યુટર ઠીક કરવા માં મદદ કરીશ.",
        "હું તમારી કાર પાર્ક કરવામાં મદદ કરીશ.",
        "હું તમારું નવા ઘરમાં જવા માટે મદદ કરીશ.",
        "હું તમારી ચેરિટી માટે પૈસા ભેગા કરવામાં મદદ કરીશ.",
        "હું આજે રાત્રે ભોજન બનાવવામાં મદદ કરીશ.",
        "હું ફરી એ ઘટનાથી બચવા માટે મદદ કરીશ.",
      ],
    },
  },
  {
    id: "basic-035",
    title: "I'm dying to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2036",
    content: {
      title: "I'm dying to + (verb)",
      detail1:
        "The phrase 'I'm dying to' means that you really want or desire to do something very much.",
      example1: [
        "I'm dying to introduce you to my parents.",
        "I'm dyning to learn more about you.",
        "I'm dying to relax on the beach.",
        "I'm dying to order some desserts.",
        "I'm dying to move to a bigger house.",
        "I'm dying to find out if I got the job.",
      ],
      titleGuj: "",
      detail1Guj:
        "'I'm dying to' વાક્યનો અર્થ એ છે કે તમે ખરેખર ખૂબ ઈચ્છો છો કે કંઈક કરવું.",
      example1Guj: [
        "હું તમને મારા માતા-પિતા સાથે ઓળખાવવાનું ખૂબ ઇચ્છું છું.",
        "હું તમારા વિશે વધુ જાણવા માટે આતુર છું.",
        "હું સમુદ્રકાંઠે આરામ કરવા માટે ખુબ ઉત્સુક છું.",
        "હું કેટલાક મીઠાઈઓનું ઓર્ડર આપવા માટે આતુર છું.",
        "હું મોટા ઘરમાં રહેવા માટે ખૂબ ઈચ્છું છું.",
        "હું જાણવા માટે ખૂબ ઉત્સુક છું કે મને નોકરી મળી કે નહીં.",
      ],
    },
  },
  {
    id: "basic-036",
    title: "It's my turn to + (verb)",
    url: "https://www.talkenglish.com/lessondetails.aspx?ALID=2037",
    content: {
      title: "It's my turn to + (verb)",
      detail1:
        "The phrase 'It's my turn to + (verb)' means that it is now your opportunity or responsibility to do something, usually after someone else has had their chance.",
      example1: [
        "It's my turn to choose where we eat.",
        "It's my turn to pay for dinner.",
        "It's my turn to roll the dice.",
        "It's my turn to provide an answer.",
        "It's my turn to try and play the game.",
        "It's my turn to attempt solving the problem.",
        "It's my turn to take out the trash.",
      ],
      titleGuj: "",
      detail1Guj:
        "'It's my turn to + (ક્રિયાપદ)' નો અર્થ છે કે હવે તમારું અવસર અથવા જવાબદારી છે કંઈક કરવા માટે, સામાન્ય રીતે પછી જ્યારે કોઈ બીજા વ્યક્તિને તક મળી હોય.",
      example1Guj: [
        "આખો વારો હવે મારો છે કે ક્યાં ખાવું તે પસંદ કરવાનું.",
        "રાત્રીભોજન માટે પેમેન્ટ કરવાનો વારો હવે મારો છે.",
        "ડાઇ ફેંકવાનો વારો હવે મારો છે.",
        "જવાબ આપવાનો વારો હવે મારો છે.",
        "ગેમ રમવાનો પ્રયાસ કરવાનો વારો હવે મારો છે",
        "સમસ્યા ઉકેલવાનો પ્રયાસ કરવાનો વારો હવે મારો છે.",
        "કચરો કાઢવાનો વારો હવે મારો છે.",
      ],
    },
  },
];
